### ISSUE TITLE
Looks like an issue with shift command

### ISSUE THREAD

**Issue by netflash** [zaxbux/syno-acme#1]
Hi there,

I tried the script and it didn't work

https://github.com/zaxbux/syno-acme/blob/bb3af167b58fb7d5dcf6f659aeb7a5b31477b0a0/acme.sh/deploy/synology_dsm_local.sh#L165

If I switch this line to `$1` instead of `$2`, and the next one to `$1`  too - it works perfectly.
Didn't spend too much time on that, but I reckon either `shift` is redundant or they should use `$1`

**Comment by zaxbux** [comment]
Thanks! I'm not sure why those were still in there.
